export type CardType =
    'artifact'
    | 'basic land'
    | 'creature'
    | 'instant'
    | 'sorcery'
    | 'creature'
    | 'enchantmnet'
    | 'land'
    | 'legendary artifact'
    | 'legendary creature'
    | 'legendary planeswalker'
